version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.9.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.5
    - 24.1.9
    - 24.2.0
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.5
  - dependency-name: "@vue/cli-plugin-vuex"
    versions:
    - 4.5.12
  - dependency-name: faker
    versions:
    - 5.5.0
    - 5.5.1
  - dependency-name: vue-cli-plugin-i18n
    versions:
    - 2.0.0
    - 2.0.2
  - dependency-name: "@vue/composition-api"
    versions:
    - 1.0.0-rc.2
    - 1.0.0-rc.3
    - 1.0.0-rc.4
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
  - dependency-name: element-ui
    versions:
    - 2.15.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
