name: CI

on: push

jobs:
  lint-css:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.JS
      uses: actions/setup-node@v1
      with:
        node-version: 14.8.0
    - run: npm install --prefer-offline --no-audit
    - run: npm run lint:css
  lint-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.JS
      uses: actions/setup-node@v1
      with:
        node-version: 14.8.0
    - run: npm install --prefer-offline --no-audit
    - run: npm run lint:js
  specs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.JS
      uses: actions/setup-node@v1
      with:
        node-version: 14.8.0
    - run: npm install --prefer-offline --no-audit
    - run: npm run test:unit
