name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.JS
      uses: actions/setup-node@v1
      with:
        node-version: 14.8.0
    - run: npm ci
    - run: npm run lint
  specs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.JS
      uses: actions/setup-node@v1
      with:
        node-version: 14.8.0
    - run: npm ci
    - run: npm run test:unit
